name: build

on:
    push:
        branches: [v7]
    pull_request:
        branches: [v7]
        types: [opened]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10.6'
                  cache: 'pip'

            - run: pip install -r ./scripts/requirements.txt

            - run: python ./scripts/build.py
              env:
                  CURSEFORGE_CORE_API_KEY: ${{secrets.CURSEFORGE_CORE_API_KEY}}

            - run: echo "PROJECT_VERSION=`cat ./tmp/version.txt`" >> $GITHUB_ENV

            - uses: actions/upload-artifact@v1
              with:
                  name: HaruhiServer-${{env.PROJECT_VERSION}}
                  path: build
