name: build

on:
    # Triggers the workflow on push or pull request events but only for the v7 branch
    #push:
    #  branches: [ v7 ]
    #pull_request:
    #  branches: [ v7 ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SERVER_DIR: ./build/server
            CLIENT_DIR: ./build/client
            ARTIFACT_DIR: ./build/artifacts

        steps:
            - uses: actions/checkout@v2

            - name: Clean build dir
              run: |
                  rm -rf ./build
                  mkdir ./build
                  mkdir ./build/artifacts

            - name: Build server pack
              run: |
                  mkdir $SERVER_DIR
                  mkdir $SERVER_DIR/openloader
                  mkdir $SERVER_DIR/openloader/data
                  cp -r ./datapack $SERVER_DIR/openloader/data/haruhiserver

            - name: Build client pack
              run: |
                  mkdir $CLIENT_DIR
                  mkdir $CLIENT_DIR/overrides
                  mkdir $CLIENT_DIR/overrides/openloader
                  mkdir $CLIENT_DIR/overrides/openloader/resources
                  cp -r ./resourcepack $CLIENT_DIR/overrides/openloader/resources/haruhiserver

            # - uses: montudor/action-zip@v1
            #   with:
            #       args: zip -r $ARTIFACT_DIR/client.zip $CLIENT_DIR
            # - uses: montudor/action-zip@v1
            #   with:
            #       args: zip -r $ARTIFACT_DIR/server.zip $SERVER_DIR
            - name: Build artifacts
              run: |
                  cp -r $CLIENT_DIR $ARTIFACT_DIR
                  cp -r $SERVER_DIR $ARTIFACT_DIR

            - name: Upload build artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: build-artifacts
                  path: $ARTIFACT_DIR
