name: build

on:
    # Triggers the workflow on push or pull request events but only for the v7 branch
    #push:
    #  branches: [ v7 ]
    #pull_request:
    #  branches: [ v7 ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            BUILD_DIR: ./build
            SERVER_DIR: ./build/server
            CLIENT_DIR: ./build/client
            ARTIFACT_DIR: ./build/artifacts

        steps:
            - uses: actions/checkout@v2

            - name: Clean build dir
              run: |
                  echo Run Number: $GITHUB_RUN_NUMBER
                  echo Run Number: ${{ github.run_number }}
                  echo SHA: $GITHUB_SHA
                  echo SHA: ${{ github.sha }}
                  echo ${GITHUB_SHA:0:7}
                  rm -rf ${{ env.BUILD_DIR }}
                  mkdir ${{ env.BUILD_DIR }}
                  mkdir ${{ env.ARTIFACT_DIR }}

            #=======#
            # BUILD #

            - name: Build server pack
              run: |
                  mkdir ${{ env.SERVER_DIR }}
                  mkdir ${{ env.SERVER_DIR }}/openloader
                  mkdir ${{ env.SERVER_DIR }}/openloader/data
                  cp -r ./datapack ${{ env.SERVER_DIR }}/openloader/data/haruhiserver

            - name: Build client pack
              run: |
                  mkdir ${{ env.CLIENT_DIR }}
                  mkdir ${{ env.CLIENT_DIR }}/overrides
                  mkdir ${{ env.CLIENT_DIR }}/overrides/openloader
                  mkdir ${{ env.CLIENT_DIR }}/overrides/openloader/resources
                  cp -r ./resourcepack ${{ env.CLIENT_DIR }}/overrides/openloader/resources/haruhiserver

            #==========#
            # ARTIFACT #

            - name: Upload server pack
              uses: actions/upload-artifact@v1
              with:
                  name: HaruhiServer-ServerPack
                  path: ${{ env.SERVER_DIR }}

            - name: Upload client pack
              uses: actions/upload-artifact@v1
              with:
                  name: HaruhiServer-ClientPack
                  path: ${{ env.CLIENT_DIR }}
